config/routes.rb
Rails.application.routes.draw do
  resources :room_plants
  resources :rooms
  resources :users
  resources :plants
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :plants, only: [:show, :index] do
        get 'search', on: :collection
      end
      resources :users
      resources :rooms
      post 'authenticate', to: 'authentication#create'
    end
  end
end

app/models/plant.rb
class Plant < ApplicationRecord

  has_many :room_plants
  has_many :rooms, through: :room_plants

  def humidity
    if self[:resistances] == "Humidity tolerant" then
      return "high"
    elsif self[:resistances] == "Drought tolerant" then
      return "low"
    end
  end

  def self.flowers
   where("flowers is not null")
  end

  def self.noflowers
    where("flowers is null")
  end

  def self.humid_proof
    where(resistances: 'Humidity tolerant')
  end

  def self.drought_proof
    where(resistances: 'Drought tolerant')
  end

  def self.light(light)
    if light == "bright"
      where('sun_requirements LIKE "%Full Sun%"')
    elsif light == "medium"
      where('sun_requirements LIKE "%Partial%"')
    elsif light == "low"
      where('sun_requirements LIKE "%Full Shade%"')
    end
  end



end

app/controllers/api/v1/plants_controller.rb
class Api::V1::PlantsController < API::V1::BaseController

  def show
    plant = Plant.find(params[:id])
    render json: plant, serializer: PlantSerializer
  end

  def index
    plants  = Plant.all

    render json: plants, each_serializer: PlantSerializer
  end  

  def search
    #term = params[:humidity] || params[:light] || params[:temperature] || params[:flowers] || nil
    term = params
    plants = []
    if term[:humidity] == "high" 
      if term[:flowers] == "true"
        plants = Plant.flowers & Plant.humid_proof & Plant.light(term[:light])
      else
        plants = (Plant.humid_proof & Plant.light(term[:light])) - Plant.flowers
      end
    else 
      if term[:flowers] == "true"
        plants = Plant.flowers & Plant.drought_proof & Plant.light(term[:light])
      else
        plants = (Plant.drought_proof & Plant.light(term[:light])) - Plant.flowers
      end
    end
    #plants = Plant.where('latin_name LIKE ?', "%#{term}%") if term
    render json: plants, each_serializer: PlantSerializer
  end

  private

  def true?(obj)
    obj.to_s == "true"
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to @plant, notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.fetch(:plant, {})
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% plant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plants</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= link_to 'Show', plant %></td>
        <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
        <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant', new_plant_path %>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<% @plant.attributes.each do |attr|%>
<tr><td><%= attr[0]%>: <%=attr[1]%></td></tr>
<%end%>
</table>
<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>